import './globals.css';
import type { Metadata } from 'next';
import { Quicksand } from 'next/font/google';
import NavBar from './components/NavBar';

export const dynamic = 'force-dynamic';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const quicksand = Quicksand({ subsets: ['latin'] });

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html data-theme="forest" className="dark" lang="en">
      <body className={quicksand.className}>
        <div className="h-screen flex flex-col">
          <header>
            <NavBar />
          </header>
          <main className="flex-grow">{children}</main>
        </div>
      </body>
    </html>
  );
}
